apiVersion: v1
kind: Service
metadata:
  name: {{ template "schema-registry.headless.service" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    {{- include "schema-registry.labels.standard" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    {{- if .Values.prometheus.jmx.enabled }}
    - name: http-metrics
      port: {{ .Values.prometheus.jmx.port }}
      targetPort: http-metrics
    {{- end }}
  {{- if .Values.hostNetwork }}
  publishNotReadyAddresses: true
  {{- end }}
  selector:
    app: {{ template "schema-registry.name" . }}
