{{- if .Values.prometheus.jmx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "schema-registry.fullname" . }}-jmx-configmap
  labels:
    {{- include "schema-registry.labels.standard" . | nindent 4 }}
data:
  jmx-schema-registry-prometheus.yml: |+
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:{{ .Values.jmx.port }}/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    rules:
      - pattern : 'kafka.schema.registry<type=jetty-metrics>([^:]+):'
        name: "cp_kafka_schema_registry_jetty_metrics_$1"
      - pattern : 'kafka.schema.registry<type=master-slave-role>([^:]+):'
        name: "cp_kafka_schema_registry_master_slave_role"
      - pattern : 'kafka.schema.registry<type=jersey-metrics>([^:]+):'
        name: "cp_kafka_schema_registry_jersey_metrics_$1"
{{- end }}
