apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "schema-registry.fullname" . }}-log-configmap
  labels:
    {{- include "schema-registry.labels.standard" . | nindent 4 }}
data:
  log4j.properties: |-
    log4j.rootLogger={{ .Values.logging.level }}, stdout

    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c:%L)%n

    log4j.logger.kafka=ERROR, stdout
    log4j.additivity.kafka=false
    {{- if .Values.logging.extraLogConfig }}
    {{- range $key,$value := .Values.logging.extraLogConfig }}
    log4j.logger.{{ $value.name }}={{ $value.level }}, stdout
    log4j.additivity.{{ $value.name }}=false
    {{- end }}
    {{- end }}