apiVersion: v1
kind: Service
metadata:
  name: {{ template "schema-registry.fullname" . }}-service
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    {{- include "schema-registry.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    {{- if .Values.prometheus.jmx.enabled }}
    - name: http-metrics
      port: {{ .Values.prometheus.jmx.port }}
      targetPort: http-metrics
    {{- end }}
  selector:
    app: {{ template "schema-registry.name" . }}
