{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) ( .Values.prometheus.jmx.enabled ) ( .Values.servicemonitor.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "schema-registry.fullname" . }}
  labels:
    monitoring: shared
    {{- include "schema-registry.labels.standard" . | nindent 4 }}
spec:
  jobLabel: app
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - {{ template "schema-registry.name" . }}
  endpoints:
    - port: http-metrics
      interval: {{ .Values.servicemonitor.interval }}
      {{- if .Values.servicemonitor.secure }}
      scheme: https
      tlsConfig:
        {{- toYaml .Values.servicemonitor.tlsConfig | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
