{{- if .Values.schemaCompatibility.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.schemaCompatibility.config.name }}
  labels:
    release: {{ .Release.Name }}
spec:
  concurrencyPolicy: {{ .Values.schemaCompatibility.cronjob.concurrencyPolicy }}
  schedule: {{ .Values.schemaCompatibility.cronjob.schedule }}
  startingDeadlineSeconds: {{ .Values.schemaCompatibility.cronjob.startingDeadlineSeconds }}
  successfulJobsHistoryLimit: {{ .Values.schemaCompatibility.cronjob.successfulJobsHistoryLimit }}
  suspend: {{ .Values.schemaCompatibility.cronjob.suspend }}
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ .Values.schemaCompatibility.cronjob.activeDeadlineSeconds }}
      template:
        metadata:
          {{- with merge .Values.schemaCompatibility.cronjob.podAnnotations .Values.commonPodAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.schemaCompatibility.cronjob.podLabels }}
          labels:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          volumes:
            - name: service-config
              configMap:
                name: {{ .Values.schemaCompatibility.config.name }}
          containers:
            - command: [ "/bin/sh", "-c" ]
              args:
                - |
                  echo "Running python script: compatibility changer"
                  cd /opt/schema-compatibility
                  /opt/venv/bin/python -m cron-job.py
              image: "{{ .Values.image.registry }}/{{ .Values.schemaCompatibility.image.repository }}:{{ default $.Chart.AppVersion .Values.schemaCompatibility.image.tagOverride }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              name: {{ .Values.schemaCompatibility.config.name }}
              {{- with .Values.schemaCompatibility.cronjob.resources }}
              resources:
                {{- toYaml . | nindent 14 }}
              {{- end }}
              volumeMounts:
                - name: service-config
                  mountPath: /app/resources/configs/schema-compatibility/application.conf
                  subPath: application.conf
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          restartPolicy: {{ .Values.schemaCompatibility.cronjob.restartPolicy }}
          affinity:
            {{- toYaml .Values.schemaCompatibility.cronjob.affinity | nindent 12 }}
          nodeSelector:
            {{- toYaml .Values.schemaCompatibility.cronjob.nodeSelector | nindent 12 }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          tolerations:
            {{- toYaml .Values.schemaCompatibility.cronjob.tolerations | nindent 12 }}
  {{- end }}
