#!/bin/sh

set -eux

echo "*** Downloading Schema Registry"
# download confluent binaries
curl -sSL http://packages.confluent.io/archive/5.5/confluent-community-$CONFLUENT_VERSION-$SCALA_VERSION.tar.gz | tar xz \
confluent-$CONFLUENT_VERSION/etc/schema-registry \
confluent-$CONFLUENT_VERSION/share/java/confluent-common \
confluent-$CONFLUENT_VERSION/share/java/rest-utils \
confluent-$CONFLUENT_VERSION/share/java/schema-registry

mv confluent-$CONFLUENT_VERSION/* .

mv etc/schema-registry/* etc/
rmdir etc/schema-registry

# hush logs including HEALTHCHECK
sed -i 's~INFO~WARN~g' etc/log4j.properties
# stop JUL spam about io.confluent.kafka.schemaregistry.rest.resources.ServerMetadataResource
echo 'org.glassfish.jersey.internal.inject.Providers = SEVERE' > etc/logging.properties

# default to listen on 8081 and connect to "kafka" hostname on default port
cat > etc/schema-registry.properties <<-EOF
avro.compatibility.level=full_transitive
kafkastore.group.id=hypertrace-schema-registry
listeners=http://0.0.0.0:8081
host.name=schema-registry
kafkastore.bootstrap.servers=PLAINTEXT://kafka:9092
master.eligibility=true
EOF

echo "*** Cleaning Up"
rm -rf confluent-$CONFLUENT_VERSION

echo "*** Image build complete"
