#!/bin/sh
# ENTRYPOINT script that starts Confluent Schema Registry
#
# This intentionally locates config using the current working directory, in order to consolidate
# Dockerfile instructions to WORKDIR

SCHEMA_REGISTRY_ENV="$(printenv | grep ^SCHEMA_REGISTRY_)"

# Enforce variable checks after we check ENV to avoid early exit
set -ue

# Only overwrite schema-registry.properties when ENV variables exist
if [ "$SCHEMA_REGISTRY_ENV" != "" ]; then
  for line in $SCHEMA_REGISTRY_ENV; do
    name=`echo $line | awk -F'=' '{print $1}' | sed 's/^SCHEMA_REGISTRY_//g' | tr '[:upper:]' '[:lower:]' | sed 's/_/./g'`
    value=`echo $line | awk -F'=' '{print $2}'`
    echo "$name=$value"
  done > etc/schema-registry.properties
fi

exec java \
  -cp 'share/java/confluent-common/*:share/java/rest-utils/*:share/java/schema-registry/*' \
  $JAVA_OPTS \
  -Dschema-registry.log.dir=logs \
  -Dlog4j.configuration=file:./etc/log4j.properties \
  io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain etc/schema-registry.properties
